### ISSUE TITLE
Safari: Overflow is not handle properly

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-modal#64]
The modal should expand to the size of the window (vertically) and get a small gap at the bottom of the content to see the full content (avoid footer to hide that content)

**Comment by dafortin** [comment]
Safari
![screen shot 2016-11-29 at 11 56 14 am](https://cloud.githubusercontent.com/assets/18552536/20719836/27727298-b62b-11e6-9fae-c49b4ec11be0.png)

**Comment by dafortin** [comment]
Chrome
![screen shot 2016-11-29 at 11 58 52 am](https://cloud.githubusercontent.com/assets/18552536/20719858/3996d914-b62b-11e6-8cd9-6e30a7e89d8f.png)

**Comment by TheOtherDude** [comment]
The issue is that Safari does not support viewport units (at least not very well), which is causing `max-height` to be calculated incorrectly. Considering how crippling this issue is on Safari, I would be happy with just using `100%` instead of `100vh` in the max-height calculation, but that would effectively break the `max-height` setting in Chrome.

**Comment by notmessenger** [comment]
Closed because we only currently support Chrome and Firefox.
